# Generated by Django 2.1.4 on 2018-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181228_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='CourseType',
            field=models.CharField(choices=[('training', '培训机构'), ('university', '高校'), ('personal', '个人')], default='training', max_length=20, verbose_name='机构类型'),
        ),
    ]
