# Generated by Django 2.1.4 on 2018-12-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20181228_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_num',
            new_name='course_nums',
        ),
    ]
