# Generated by Django 2.1.4 on 2018-12-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20181228_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='CourseType',
            new_name='courseType',
        ),
    ]
