# Generated by Django 2.1.4 on 2018-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_courseorg_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(default=25, verbose_name='年龄'),
        ),
    ]
