# Generated by Django 2.1.4 on 2018-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='课程类型'),
        ),
    ]
