# Generated by Django 2.1.4 on 2018-12-30 21:33

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_image'),
        ('courses', '0004_courses_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=organization.models.Teacher, null=organization.models.Teacher, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='所属讲师'),
            preserve_default=organization.models.Teacher,
        ),
        migrations.AddField(
            model_name='courses',
            name='you_get',
            field=models.CharField(default='', max_length=100, verbose_name='你能学到的'),
        ),
        migrations.AddField(
            model_name='courses',
            name='you_need',
            field=models.CharField(default='', max_length=100, verbose_name='须知'),
        ),
    ]
