# Generated by Django 2.1.4 on 2019-01-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverityrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverityrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回账号'), ('change', '修改邮箱')], default='register', max_length=30),
        ),
    ]
